"""The frozen E2 analysis identity (freeze v2).

Two identities are kept apart. The matrix identity (``matrix.py``) says which
matches the experiment runs; it changes only when the experimental design
does. The freeze identity says which complete instrument interprets those
matches: it carries the matrix id and digest, the pre-registration digest,
the capture analyzer's version and digest, the SHA-256 of every
analysis-tooling file and the Git commit those files were qualified at, and
the match-generation source the reused control corpus was produced by.
Repairing analysis tooling changes the freeze identity, never the matrix
identity.

Freeze v1 was the original freeze at ``062feeb`` (matrix id, pre-registration
digest, capture analyzer version 1; ``docs/research/v6/V6_E2_EXPERIMENT_FREEZE.md``).
Its analyzer could not process a core that wraps the arena end, and the matrix
halted before T-E2 (``V6_E2_MATRIX_EXECUTION_HALT.md``). Freeze v2 repairs the
analyzer, keeps the matrix id, and reuses the C-V4 / C-RS corpus generated at
``062feeb``; T-E2 must be generated by that same match-generation source.

``analysis_freeze.json`` is the committed freeze record. Loading it fails
closed unless its digest recomputes and every live input -- tooling files,
matrix, pre-registration, analyzer version -- still equals the record.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
from pathlib import Path
from typing import Any

from tools.research.v6.e2 import matrix
from tools.research.v6.e2.capture_analyzer import CAPTURE_ANALYZER_VERSION
from tools.research.v6.e2.preregistration import preregistration_digest
from tools.research.v6.experiment_harness import REPO_ROOT

FREEZE_VERSION = 2
FREEZE_SCHEMA = "bytefray.v6.e2.analysis_freeze"
FREEZE_RECORD_PATH = Path(__file__).with_name("analysis_freeze.json")

CAPTURE_ANALYZER_FILE = "tools/research/v6/e2/capture_analyzer.py"
# The complete analysis instrument: every file whose content can change how a
# match is planned, checked, gated or interpreted. The freeze record itself is
# the only E2 tooling file outside its own digest.
TOOLING_FILES: tuple[str, ...] = (
    "tools/research/v6/experiment_harness.py",
    "tools/research/v6/e2/analysis_freeze.py",
    "tools/research/v6/e2/analyze_e2.py",
    CAPTURE_ANALYZER_FILE,
    "tools/research/v6/e2/control_gate.py",
    "tools/research/v6/e2/matrix.py",
    "tools/research/v6/e2/preregistration.json",
    "tools/research/v6/e2/preregistration.py",
    "tools/research/v6/e2/requalification.py",
    "tools/research/v6/e2/run_e2.py",
)

# The reused C-V4 / C-RS corpus was generated at this commit (freeze v1), and
# T-E2 must be generated by the identical engine source.
CONTROL_SOURCE_SHA = "062feeb28d84c8da0af3f41716e3b5468e0b3eed"
MATCH_GENERATION_PATH = "engine/src"


class AnalysisFreezeError(RuntimeError):
    """The E2 analysis instrument does not match its frozen identity."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def file_sha256(relative: str, repo_root: Path = REPO_ROOT) -> str:
    """SHA-256 of a repository file with line endings normalized to LF."""
    return _sha256((repo_root / relative).read_bytes())


def _git(*args: str) -> bytes:
    return subprocess.check_output(["git", *args], cwd=REPO_ROOT)


def git_text(*args: str) -> str:
    return _git(*args).decode("utf-8").strip()


def identity_inputs(*, tooling_source_sha: str, match_generation_tree: str) -> dict[str, Any]:
    """The inputs the freeze identity is a digest of, read from the live checkout."""
    return {
        "freeze_version": FREEZE_VERSION,
        "matrix_id": matrix.matrix_id(),
        "matrix_digest": matrix.E2_MATRIX_DIGEST,
        "preregistration_sha256": preregistration_digest(),
        "capture_analyzer_version": CAPTURE_ANALYZER_VERSION,
        "capture_analyzer_sha256": file_sha256(CAPTURE_ANALYZER_FILE),
        "tooling_sha256": {path: file_sha256(path) for path in TOOLING_FILES},
        "tooling_source_sha": tooling_source_sha,
        "control_source_sha": CONTROL_SOURCE_SHA,
        "match_generation_path": MATCH_GENERATION_PATH,
        "match_generation_tree": match_generation_tree,
    }


def freeze_digest(identity: dict[str, Any]) -> str:
    canonical = json.dumps(identity, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def freeze_id(identity: dict[str, Any]) -> str:
    return f"v6-e2-freeze-v{identity['freeze_version']}-{freeze_digest(identity)[:12]}"


def build_freeze_record(identity: dict[str, Any], requalification: dict[str, Any]) -> dict[str, Any]:
    """A freeze record; ``requalification`` summarizes its control-data evidence
    and is outside the identity digest."""
    return {
        "schema": FREEZE_SCHEMA,
        "freeze_id": freeze_id(identity),
        "freeze_digest": freeze_digest(identity),
        "identity": identity,
        "requalification": requalification,
    }


def candidate_identity() -> dict[str, Any]:
    """The would-be freeze of the current clean checkout, before a record is committed."""
    if git_text("status", "--porcelain"):
        raise AnalysisFreezeError("A candidate analysis freeze needs a clean tracked tree.")
    identity = identity_inputs(
        tooling_source_sha=git_text("rev-parse", "HEAD"),
        match_generation_tree=git_text("rev-parse", f"{CONTROL_SOURCE_SHA}:{MATCH_GENERATION_PATH}"),
    )
    return build_freeze_record(identity, {})


def load_freeze(path: Path = FREEZE_RECORD_PATH) -> dict[str, Any]:
    """The committed freeze record; fails closed on any drift from the live checkout."""
    if not path.is_file():
        raise AnalysisFreezeError(f"No analysis freeze record at {path}; freeze the analysis first.")
    record: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    identity = record.get("identity") or {}
    problems: list[str] = []
    if record.get("schema") != FREEZE_SCHEMA:
        problems.append(f"schema {record.get('schema')!r}")
    if record.get("freeze_digest") != freeze_digest(identity) or record.get("freeze_id") != freeze_id(identity):
        problems.append("the record's digest or id does not recompute from its identity")
    if identity.get("freeze_version") != FREEZE_VERSION:
        problems.append(f"freeze_version {identity.get('freeze_version')!r} != {FREEZE_VERSION}")
    else:
        live = identity_inputs(
            tooling_source_sha=str(identity.get("tooling_source_sha")),
            match_generation_tree=str(identity.get("match_generation_tree")),
        )
        for key, value in live.items():
            if key == "tooling_sha256":
                recorded = identity.get(key) or {}
                changed = sorted(p for p in set(value) | set(recorded) if value.get(p) != recorded.get(p))
                if changed:
                    problems.append(f"tooling files changed since the freeze: {changed}")
            elif identity.get(key) != value:
                problems.append(f"{key} {identity.get(key)!r} != live {value!r}")
    if problems:
        raise AnalysisFreezeError("E2 analysis freeze does not hold: " + "; ".join(problems))
    return record


def current_freeze(path: Path = FREEZE_RECORD_PATH) -> dict[str, Any]:
    """The committed freeze if one exists, otherwise the clean checkout's candidate."""
    return load_freeze(path) if path.is_file() else candidate_identity()


def verify_execution_source(record: dict[str, Any]) -> None:
    """Before any T-E2 match runs: a clean tree, engine source identical to the
    source that generated the reused controls, and every tooling file identical
    to its content at the commit the freeze was qualified at."""
    identity = record["identity"]
    problems: list[str] = []
    if git_text("status", "--porcelain"):
        problems.append("the tracked tree is not clean")
    live_tree = git_text("rev-parse", f"HEAD:{identity['match_generation_path']}")
    if live_tree != identity["match_generation_tree"]:
        problems.append(
            f"{identity['match_generation_path']} tree {live_tree} differs from the control "
            f"corpus's {identity['match_generation_tree']} (generated at {identity['control_source_sha']})"
        )
    for path, digest in sorted(identity["tooling_sha256"].items()):
        try:
            committed = _sha256(_git("show", f"{identity['tooling_source_sha']}:{path}"))
        except subprocess.CalledProcessError:
            committed = None
        if committed != digest:
            problems.append(f"{path} at {identity['tooling_source_sha']} differs from the freeze")
    if problems:
        raise AnalysisFreezeError("T-E2 execution source check failed: " + "; ".join(problems))
