"""The E5 pre-treatment gates at non-matrix seeds (review Sec L gates 5-7).

Every gate runs named scenarios only, at seeds outside the matrix's 1..32,
and records pass/fail evidence -- identities, hashes and counts -- never a
gameplay outcome metric of the treatment. Each has a sensitivity case that
must *fail*, so a passing gate is shown able to see what it checks.

* **P5 inertness** (review Sec F, Revision 1 decision R1-5). For every E5
  pairing that contains a fixture following the single-location core-inference
  contract, the frozen fixture and a *test-only* offset-aware copy (the same
  code with its enemy-core adoption corrected by its own spawn offset) must
  play byte-identical tick records under the primary treatment. The copies
  are generated by ``offset_aware_source`` into a temporary data root and
  never enter the matrix, the populations or the analysis. Sensitivity: with
  the spawn moved to ``core_base - 2`` (a scratch patch of the resolver), at
  least one pairing must differ.
* **Observation delta** (review Sec L gate 5). For every E5 pairing, each
  entrant's first observation under a treatment differs from the parent's only
  in ``self_anchor`` (-1) and in each visible enemy anchor (-1). Sensitivity:
  comparing the parent with itself shifted by the patch above must fail.
* **D9 real-fixture gate** (G.5). E3's D9 scenarios, unchanged, under T-E5:
  the real repair and disrupt guards against scripted adversaries are never
  captured. Sensitivity: the whole-tick E2 Ruleset captures the repair guard.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import tempfile
from collections.abc import Callable, Iterator, Sequence
from contextlib import contextmanager
from pathlib import Path
from typing import Any

from battle_engine.agent_api import AgentAction, ObservationV2
from battle_engine.agents import resolve_agent
from battle_engine.config import Config
from battle_engine.match_service import MatchEntrant, MatchRequest, NativeMatchService
from battle_engine.placement import resolve_direct_match_starts
from battle_engine.process_runtime import ProcessMatchController
from battle_engine.ruleset_policy import (
    BYTEFRAY_RULESET_V6_RESEARCH_CAPTURE_HOLD_K2_ID,
    RulesetPolicy,
    resolve_ruleset_policy,
)

from tools.research.v6.e3 import d9_gate as e3_d9
from tools.research.v6.e3.entrants import prepare_data_root
from tools.research.v6.e4.gates import tick_lines
from tools.research.v6.e5 import matrix

NONMATRIX_GATES_VERSION = 1
SEEDS: tuple[int, ...] = (101, 102, 103, 104)
OBSERVATION_SEEDS: tuple[int, ...] = (101, 102)
PRIMARY_ID = matrix.condition(matrix.PRIMARY_TREATMENT).ruleset_id
COMPANION_ID = matrix.condition(matrix.COMPANION_TREATMENT).ruleset_id
PARENT_ID = {PRIMARY_ID: matrix.condition(matrix.PRIMARY_CONTROL).ruleset_id,
             COMPANION_ID: matrix.condition(matrix.COMPANION_CONTROL).ruleset_id}
INERTNESS_RECORD_NAME = "p5_inertness_gate.json"
OBSERVATION_RECORD_NAME = "observation_delta_gate.json"
D9_RECORD_NAME = "d9_real_fixture_gate.json"
AWARE_PREFIX = "e5gate_aware_"

# The one text transformation that makes an inferring fixture offset-aware.
_ACT = "    def act(self, obs: ObservationV2) -> AgentAction:\n"
_ADOPT = "self.enemy_core = anchors[0]"
_OFFSET = ("        if getattr(self, '_own_off', None) is None:\n"
           "            self._own_off = (obs.self_anchor - obs.own_core_base) % self.arena\n")
_ADOPT_AWARE = "self.enemy_core = (anchors[0] - self._own_off) % self.arena"


class NonMatrixGateError(RuntimeError):
    """A pre-treatment non-matrix gate has not passed."""


def _check_seeds(seeds: Sequence[int]) -> None:
    if set(seeds) & set(matrix.SEEDS):
        raise NonMatrixGateError("Non-matrix gates must not use matrix seeds (1..32).")


def offset_aware_source(text: str) -> str:
    """The test-only offset-aware variant of an inferring fixture's ``agent.py``:
    it records its own spawn offset (self_anchor - own_core_base) at its first
    callback, before any move, and adopts ``anchor - offset`` as the enemy core."""
    if text.count(_ACT) != 1 or text.count(_ADOPT) != 1:
        raise NonMatrixGateError("fixture source does not have exactly one act() and one core adoption")
    return text.replace(_ACT, _ACT + _OFFSET).replace(_ADOPT, _ADOPT_AWARE)


def inferring(agent: str) -> bool:
    return agent in matrix.CORE_INFERRING_AGENTS


def inertness_pairings() -> list[tuple[str, str]]:
    """Every E5 ordered pairing (F1 both orientations, F2 one orientation) with an inferring fixture."""
    pairs = [(a, b) for a, b in matrix.F1.pairs if inferring(a) or inferring(b)]
    ordered = [pair for a, b in pairs for pair in ((a, b), (b, a))]
    return ordered + [(a, b) for a, b in matrix.F2.pairs if inferring(a)]


def prepare_aware_root(dest: Path) -> tuple[Path, dict[str, str]]:
    """A data root holding every E5 fixture and an offset-aware copy of each inferring one.
    Returns the root and ``{copy name: sha256 of its agent.py}``."""
    root = prepare_data_root(dest, [*matrix.E5_AGENTS, *matrix.E5_TWINS])
    digests: dict[str, str] = {}
    for name in sorted(matrix.CORE_INFERRING_AGENTS):
        source = root / "agents" / name
        copy = root / "agents" / f"{AWARE_PREFIX}{name}"
        shutil.copytree(source, copy, ignore=shutil.ignore_patterns("__pycache__"))
        text = offset_aware_source((copy / "agent.py").read_text(encoding="utf-8"))
        (copy / "agent.py").write_bytes(text.encode("utf-8"))
        manifest = (copy / "agent.yaml").read_text(encoding="utf-8").splitlines()
        (copy / "agent.yaml").write_bytes(("\n".join(
            f"name: {AWARE_PREFIX}{name}" if line.startswith("name:") else line for line in manifest) + "\n"
        ).encode("utf-8"))
        digests[copy.name] = hashlib.sha256(text.encode("utf-8")).hexdigest()
    return root, digests


def _aware(name: str) -> str:
    return f"{AWARE_PREFIX}{name}" if inferring(name) else name


def _play(root: Path, out: Path, ruleset_id: str, names: tuple[str, str], seed: int, ticks: int) -> list[str]:
    starts = resolve_direct_match_starts(ruleset_id=ruleset_id, arena_size=matrix.ARENA_SIZE, entrant_count=2,
                                         supplied_starts=[None, None], seed=seed)
    replay = out / "replay.jsonl"
    replay.parent.mkdir(parents=True, exist_ok=True)
    NativeMatchService().run(MatchRequest(
        config=Config(seed=seed, arena_size=matrix.ARENA_SIZE, instr_per_tick=matrix.QUOTA),
        entrants=tuple(MatchEntrant.python(seat, name, start, resolve_agent(root, name))
                       for seat, name, start in zip("AB", names, starts, strict=True)),
        max_ticks=ticks, replay_path=replay, verbose=False, ruleset_id=ruleset_id))
    return tick_lines(replay)


@contextmanager
def spawn_offset_patch(offset: int) -> Iterator[None]:
    """Scratch sensitivity patch: under ``before_core`` spawn at ``core_base - offset``."""
    original = RulesetPolicy.resolve_initial_anchor

    def patched(self: RulesetPolicy, core_base: int, arena_size: int) -> int:
        if self.initial_anchor_placement == "before_core":
            return (core_base - offset) % arena_size
        return original(self, core_base, arena_size)

    RulesetPolicy.resolve_initial_anchor = patched  # type: ignore[method-assign]
    try:
        yield
    finally:
        RulesetPolicy.resolve_initial_anchor = original  # type: ignore[method-assign]


def _compare(root: Path, base: Path, pairings: Sequence[tuple[str, str]], seeds: Sequence[int], ticks: int,
             tag: str) -> list[dict[str, Any]]:
    rows = []
    for a, b in pairings:
        for seed in seeds:
            frozen = _play(root, base / tag / f"{a}-{b}-{seed}-frozen", PRIMARY_ID, (a, b), seed, ticks)
            aware = _play(root, base / tag / f"{a}-{b}-{seed}-aware", PRIMARY_ID, (_aware(a), _aware(b)), seed, ticks)
            rows.append({"pairing": f"{a}|{b}", "seed": seed, "identical": frozen == aware,
                         "frozen_ticks_sha256": hashlib.sha256("\n".join(frozen).encode()).hexdigest(),
                         "aware_ticks_sha256": hashlib.sha256("\n".join(aware).encode()).hexdigest()})
    return rows


def run_inertness(work_dir: Path | None = None, *, seeds: Sequence[int] = SEEDS, ticks: int = matrix.MAX_TICKS,
                  sensitivity_seeds: Sequence[int] = (SEEDS[0],)) -> dict[str, Any]:
    _check_seeds([*seeds, *sensitivity_seeds])
    pairings = inertness_pairings()
    with tempfile.TemporaryDirectory(prefix="e5-p5-") as tmp:
        base = Path(work_dir) if work_dir is not None else Path(tmp)
        root, digests = prepare_aware_root(base / "env")
        rows = _compare(root, base, pairings, seeds, ticks, "p5")
        with spawn_offset_patch(2):
            sensitivity = _compare(root, base, pairings, sensitivity_seeds, ticks, "p5-minus-2")
    differing = [f"{row['pairing']}@{row['seed']}" for row in rows if not row["identical"]]
    detected = [f"{row['pairing']}@{row['seed']}" for row in sensitivity if not row["identical"]]
    passed = bool(rows) and not differing and bool(detected)
    return {
        "gate": "P5-inertness", "gate_version": NONMATRIX_GATES_VERSION, "ruleset_id": PRIMARY_ID,
        "seeds": list(seeds), "ticks": ticks, "pairings": [f"{a}|{b}" for a, b in pairings],
        "comparisons": len(rows), "differing": differing, "offset_aware_copy_sha256": digests,
        "sensitivity": {"offset": -2, "seeds": list(sensitivity_seeds), "comparisons": len(sensitivity),
                        "detected_differences": len(detected), "samples": detected[:10]},
        "rows": rows, "status": "PASS" if passed else "FAIL",
    }


def first_observations(root: Path, ruleset_id: str, names: tuple[str, str], seed: int) -> dict[str, dict[str, Any]]:
    """Each seat's first observation of the match (one tick)."""
    starts = resolve_direct_match_starts(ruleset_id=ruleset_id, arena_size=matrix.ARENA_SIZE, entrant_count=2,
                                         supplied_starts=[None, None], seed=seed)
    entrants = tuple(MatchEntrant.python(seat, name, start, resolve_agent(root, name))
                     for seat, name, start in zip("AB", names, starts, strict=True))
    controller = ProcessMatchController.from_python_entrants(
        Config(seed=seed, arena_size=matrix.ARENA_SIZE, instr_per_tick=matrix.QUOTA), entrants, 1,
        ruleset_policy=resolve_ruleset_policy(ruleset_id))
    seen: dict[str, dict[str, Any]] = {}
    try:
        for spec in controller.entrant_specs:
            for process in spec.processes:
                inner = process.executor
                assert inner is not None

                def record(obs: ObservationV2, slot: int, *, _seat: str = spec.agent_id,
                           _inner: Callable[[ObservationV2, int], AgentAction] = inner) -> AgentAction:
                    seen.setdefault(_seat, dict(vars(obs)))
                    return _inner(obs, slot)

                process.executor = record
        controller.run()
    finally:
        controller.close()
    return seen


def observation_delta_ok(parent: dict[str, Any], treatment: dict[str, Any], shift: int = 1) -> bool:
    arena = matrix.ARENA_SIZE
    expected = {**parent, "self_anchor": (parent["self_anchor"] - shift) % arena,
                "visible_enemy_anchor_addresses": tuple(sorted((a - shift) % arena
                                                               for a in parent["visible_enemy_anchor_addresses"]))}
    return treatment == expected


def run_observation(work_dir: Path | None = None, *, seeds: Sequence[int] = OBSERVATION_SEEDS) -> dict[str, Any]:
    _check_seeds(seeds)
    pairings = [pair for a, b in matrix.F1.pairs for pair in ((a, b), (b, a))] + list(matrix.F2.pairs)
    rows: list[dict[str, Any]] = []
    sensitivity: list[bool] = []
    with tempfile.TemporaryDirectory(prefix="e5-obs-") as tmp:
        base = Path(work_dir) if work_dir is not None else Path(tmp)
        root = prepare_data_root(base / "env", [*matrix.E5_AGENTS, *matrix.E5_TWINS])
        for ruleset_id in (PRIMARY_ID, COMPANION_ID):
            for a, b in pairings:
                for seed in seeds:
                    parent = first_observations(root, PARENT_ID[ruleset_id], (a, b), seed)
                    treatment = first_observations(root, ruleset_id, (a, b), seed)
                    ok = set(parent) == set(treatment) == {"A", "B"} and all(
                        observation_delta_ok(parent[s], treatment[s]) for s in "AB")
                    rows.append({"ruleset_id": ruleset_id, "pairing": f"{a}|{b}", "seed": seed, "ok": ok})
                    if ruleset_id == PRIMARY_ID and seed == seeds[0]:
                        # Sensitivity: the delta check must reject a -2 shift.
                        sensitivity.append(all(observation_delta_ok(parent[s], treatment[s], shift=2) for s in "AB"))
    failing = [f"{r['ruleset_id']}:{r['pairing']}@{r['seed']}" for r in rows if not r["ok"]]
    passed = bool(rows) and not failing and bool(sensitivity) and not any(sensitivity)
    return {"gate": "observation-delta", "gate_version": NONMATRIX_GATES_VERSION, "seeds": list(seeds),
            "comparisons": len(rows), "failing": failing[:20], "failure_count": len(failing),
            "sensitivity": {"shift": 2, "cases": len(sensitivity), "wrongly_accepted": sum(sensitivity)},
            "status": "PASS" if passed else "FAIL"}


def run_d9(work_dir: Path | None = None, *, seeds: Sequence[int] = e3_d9.SEEDS, ticks: int = e3_d9.TICKS,
           adversaries: Sequence[str] = tuple(e3_d9.ADVERSARIES)) -> dict[str, Any]:
    """E3's D9 scenarios, unchanged, under T-E5; sensitivity under the whole-tick E2 Ruleset."""
    _check_seeds(seeds)
    whole_tick = BYTEFRAY_RULESET_V6_RESEARCH_CAPTURE_HOLD_K2_ID
    with tempfile.TemporaryDirectory(prefix="e5-d9-") as tmp:
        base = Path(work_dir) if work_dir is not None else Path(tmp)
        data_root = prepare_data_root(base / "env", [*e3_d9.GUARDS, e3_d9.ADVERSARY_HOST])
        rows: dict[str, list[dict[str, Any]]] = {PRIMARY_ID: [], whole_tick: []}
        for ruleset_id, scenarios in rows.items():
            for guard in e3_d9.GUARDS:
                for guard_seat in ("A", "B"):
                    for adversary in adversaries:
                        for seed in seeds:
                            tag = f"{ruleset_id}/{guard}-{guard_seat}-{adversary}-{seed}"
                            scenarios.append(e3_d9.play_scenario(
                                data_root, base / "runs" / tag, ruleset_id=ruleset_id, guard=guard,
                                guard_seat=guard_seat, adversary=adversary, seed=seed, ticks=ticks))
    primary, sensitivity = rows[PRIMARY_ID], rows[whole_tick]
    failures = [row for row in primary if not e3_d9.scenario_ok(row)]
    captured = sum(1 for row in sensitivity if row["guard"] == "e2_repair_guard" and row["guard_completions"])
    passed = bool(primary) and not failures and captured > 0
    return {"gate": "D9-real-fixture", "gate_version": NONMATRIX_GATES_VERSION, "primary_ruleset": PRIMARY_ID,
            "sensitivity_ruleset": whole_tick, "guards": list(e3_d9.GUARDS), "adversaries": list(adversaries),
            "seeds": list(seeds), "ticks": ticks, "primary_scenarios": len(primary),
            "primary_guard_completions": sum(row["guard_completions"] for row in primary),
            "primary_failure_count": len(failures), "primary_failures": failures[:10],
            "sensitivity_repair_guard_captured_scenarios": captured, "status": "PASS" if passed else "FAIL"}


def write_record(path: Path, record: dict[str, Any], *, freeze_id: str, provenance: dict[str, Any]) -> dict[str, Any]:
    full = {**record, "freeze_id": freeze_id, "provenance": provenance}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(full, indent=2, sort_keys=True), encoding="utf-8")
    return full


def require_gate(path: Path, *, freeze_id: str) -> dict[str, Any]:
    if not path.is_file():
        raise NonMatrixGateError(f"No gate record at {path}.")
    record: dict[str, Any] = json.loads(path.read_text(encoding="utf-8"))
    if record.get("freeze_id") != freeze_id or record.get("status") != "PASS":
        raise NonMatrixGateError(f"{path.name} does not permit treatment (freeze {record.get('freeze_id')!r}, "
                                 f"status {record.get('status')!r})")
    return record
